version: '3'

services:
  app:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: node
    restart: always
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    depends_on: 
      - db    

  db:
    image: mysql:5.7               
    command: --innodb-use-native-aio=0
    container_name: mysql_db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=password      

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "8080:80"
    depends_on: 
      - db
      - app